List<String> functionalAreaLists = [
  "Accounts / Taxation / Audit / Company Secretary",
  "Administration",
  "Advertising / Media Planning / PR",
  "Architecture / Interior Design",
  "Buying / Purchase / Procurement / Vendor Management",
  "Cabin Crew / Flight Attendant / Steward / Air Hostess",
  "Cashier / Teller / Billing & Payment",
  "Chefs / F&B / Housekeeping / Front Desk",
  "Contract Management / Estimation / Tendering / Quantity Surveying",
  "Corporate Planning / Consulting / Strategy / M&A",
  "Data Entry / Operations / Back Office Processing",
  "DBA / Datawarehousing (IT Software)",
  "Doctor / Nurse / Paramedics / Hospital Technicians / Medical Research",
  "Drilling",
  "Engineering",
  "Equipment Operations - Machine / Crane / Forklift",
  "ERP / CRM (IT Software)",
  "Finance / Treasury",
  "Flight Operations (Pilots / Technical Staff / Ground Staff)",
  "Fresh Graduates / Management Trainee/ Intern / No Experience",
  "Geotechnical / Geologists / Petrophysicist",
  "Graphic Design / Web Design / Art / Visualiser",
  "Guards / Security Services",
  "Helpdesk / Customer Service / Telecalling",
  "HR / Human Relations/ Industrial Relations",
  "HSE (Health / Safety / Environment)",
  "Installation / Maintenance / Operations / Repair",
  "Insurance / Underwriting / Surveying / Actuary",
  "IT Hardware Support / IT Hardware Repair & Maintenance",
  "IT Software",
  "Journalism / Content Writing / Editing / Correspondent",
  "Language Translation",
  "Lawyers / Legal Advisors",
  "Logistics / Supply Chain",
  "Marine Services (Marine Officer / Marine Engineer / Ship Chandler / Diver)",
  "Marketing / Brand Management / Marketing Research / Digital Marketing",
  "MEP (Mechanical / Electrical / Plumbing)",
  "Merchandising & Planning / Category Management",
  "Product Development / Product Management",
  "Production / Manufacturing",
  "Quality / Testing / QA / QC / Inspector",
  "R&D / Research & Development",
  "Sales / Business Development",
  "Secretary / Front Office/ Personal Assistant (PA)",
  "Shop Drawing / Drafting / Draughtsman",
  "Site Engineering / Projects",
  "Software Development / Application Development (IT Software)",
  "Store Operations (for retail industry)",
  "Surveying (Civil)",
  "System Administration / Network Administration / Security (IT Software)",
  "Teaching / Education",
  "Telecom Engineering / Communications Engineering",
  "Ticketing / Reservations",
  "Top Management / Senior Management",
  "Training / Learning",
  "Transport / Driving",
  "TV Anchors / Reporters / Film Production / RJ / VJ",
  "Visual Merchandizing"
];
