List<String>  industryLists = ["Accounting & Auditing", 
"Advertising / PR / Event Management", 
"Agriculture / Dairy / Poultry / Livestock", 
"Air Conditioning / Refrigeration / HVAC", 
"Airlines / Aviation", 
"Architecture / Interior Designing", 
"Automotive / Automobile / Auto Accessories", 
"Banking / Financial Services / Broking", 
"Call Center / BPO / KPO / Outsourcing", 
"Ceramics / Sanitary ware", 
"Chemicals / Petrochemicals / Polymers / Industrial Gases", 
"Concrete / Readymix / Cement", 
"Construction / Civil Engineering", 
"Consulting / Management Consulting / Advisory Services", 
"Consumer Durables / Consumer Electronics", 
"Defence / Military / Government", 
"Education / Training / Teaching / Academics", 
"Elevators / Escalators", 
"Engineering Design & Consulting", 
"Entertainment / Recreation / Theme Parks", 
"Facilities Management", 
"Fertilizers / Pesticides", 
"Fitness / Wellness / Gym / Salon / Spa", 
"FMCG / Foods / Beverages", 
"Fresher - No Industry Experience / Not Employed", 
"Furniture / Furnishings / Home Decor", 
"General Trading / Export / Import", 
"Glass", 
"Gold / Gems & Jewellery", 
"Hotels / Hospitality",
 "Industrial Products / Heavy Machinery", 
 "Insurance", 
 "Internet / E-commerce / Dotcom", 
 "IT - Hardware & Networking", 
 "IT - Software Services", 
 "Landscaping", 
 "Legal / Law Firm", 
 "Logistics / Transportation / Warehousing / Courier", 
 "Media / Publishing / TV / Radio / Outdoor / Digital", 
 "Medical / Healthcare / Diagnostics / Medical Devices", 
 "Metals / Steel / Iron / Aluminium / Fabrication", 
 "Metro / Railway / Train", 
 "Mining / Forestry / Fishing", 
 "NGO / Social Services / Community Services / Non-Profit", 
 "Office Automation / Office Equipment / Office Supplies / Stationery", 
 "Oil & Gas / Petroleum", 
 "Oil & Gas: Consultancy, Design, FEED", 
 "Oil & Gas: Exploration, Drilling, Production, Field Services", 
 "Oil & Gas: Refining, Storage, Marketing, Distribution", 
 "Paper / Paper Pulp / Paper Mill", 
 "Perfumery / Toiletries / Personal Care / Cosmetics", 
 "Pharma / Biotech / Clinical Research", 
 "Plastics / Rubber", 
 "Power Generation / Power Distribution / Energy / Nuclear Energy", 
 "Printing / Packaging", 
 "Real Estate", 
 "Recruitment / Placement Firm / Executive Search", 
 "Restaurants / Catering / Food Services", 
 "Retail", "Security / Law Enforcement", 
 "Shipbuilding / Ship Repair / Ship Maintenance / Drydocks", 
 "Shipping / Freight", 
 "Telecom / ISP", 
 "Testing / Inspection / Certification Services", 
 "Textiles Clothing / Apparels / Fashion / Accessories", 
 "Travel / Tourism", 
 "Tyres", 
 "Water Treatment / De-Salination / Waste Management"];