List<String> skills = [
  "Communication Skills",
  "Team Collaboration",
  "Problem-Solving",
  "Time Management",
  "Critical Thinking",
  "Adaptability",
  "Leadership",
  "Interpersonal Skills",
  "Analytical Thinking",
  "Software Development",
  "Python",
  "Java",
  "C#",
  "JavaScript",
  "Full-Stack Development",
  "Mobile App Development",
  "Flutter",
  "React Native",
  "Version Control",
  "Git/GitHub",
  "Cloud Computing",
  "AWS",
  "Azure",
  "GCP",
  "Machine Learning/AI",
  "Data Analysis",
  "Python",
  "R",
  "SQL",
  "Big Data Tools",
  "Hadoop",
  "Spark",
  "Data Visualization",
  "Tableau",
  "Power BI",
  "Statistical Analysis",
  "Predictive Modeling",
  "Network Security",
  "System Administration",
  "IT Support",
  "Troubleshooting",
  "Graphic Design",
  "Adobe Photoshop",
  "Illustrator",
  "UX/UI Design",
  "Motion Graphics",
  "Video Editing",
  "Digital Marketing",
  "SEO/SEM",
  "Social Media Management",
  "Content Creation",
  "Brand Strategy",
  "Email Marketing",
  "Financial Analysis",
  "Budgeting and Forecasting",
  "Taxation",
  "Auditing",
  "Patient Care",
  "Medical Coding",
  "Clinical Research",
  "Health Informatics",
  "CAD Design",
  "Quality Assurance",
  "Automation",
  "Safety Protocols",
  "Curriculum Development",
  "Classroom Management",
  "Online Teaching Tools",
  "Zoom",
  "Google Classroom",
  "Client Relationship Management",
  "Call Handling",
  "Issue Resolution",
  "Multitasking",
  "Project Management",
  "Strategic Planning",
  "Decision-Making"
];
