// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-JAbR4pECSx1PQgBr2FAO91xmx8PGsLM',
    appId: '1:970557705658:web:a25ff608304c80b1dce183',
    messagingSenderId: '970557705658',
    projectId: 'jobseekerapp-56c86',
    authDomain: 'jobseekerapp-56c86.firebaseapp.com',
    storageBucket: 'jobseekerapp-56c86.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPNRFw2jCLsGMXFsq8whIkT82fQ1re-OA',
    appId: '1:970557705658:android:1bf8c934ecee9da1dce183',
    messagingSenderId: '970557705658',
    projectId: 'jobseekerapp-56c86',
    storageBucket: 'jobseekerapp-56c86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAJYaM4JRk66CPthdKizzE34Pinu1QtfY',
    appId: '1:970557705658:ios:d4502c784e320563dce183',
    messagingSenderId: '970557705658',
    projectId: 'jobseekerapp-56c86',
    storageBucket: 'jobseekerapp-56c86.firebasestorage.app',
    androidClientId: '970557705658-sjcntps8jdfv0sauolp43bkuk9ptu05c.apps.googleusercontent.com',
    iosClientId: '970557705658-6na12deh0harnhu1cmd4mc3h01fcu7m1.apps.googleusercontent.com',
    iosBundleId: 'com.example.recruiterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAJYaM4JRk66CPthdKizzE34Pinu1QtfY',
    appId: '1:970557705658:ios:d4502c784e320563dce183',
    messagingSenderId: '970557705658',
    projectId: 'jobseekerapp-56c86',
    storageBucket: 'jobseekerapp-56c86.firebasestorage.app',
    androidClientId: '970557705658-sjcntps8jdfv0sauolp43bkuk9ptu05c.apps.googleusercontent.com',
    iosClientId: '970557705658-6na12deh0harnhu1cmd4mc3h01fcu7m1.apps.googleusercontent.com',
    iosBundleId: 'com.example.recruiterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-JAbR4pECSx1PQgBr2FAO91xmx8PGsLM',
    appId: '1:970557705658:web:6a70c2495fb6b5b6dce183',
    messagingSenderId: '970557705658',
    projectId: 'jobseekerapp-56c86',
    authDomain: 'jobseekerapp-56c86.firebaseapp.com',
    storageBucket: 'jobseekerapp-56c86.firebasestorage.app',
  );
}
